#!/usr/bin/env python3

print("Power a.k.a. exponentiation:")
print("3 to the 3rd power is", 3 ** 3)
print("")
print("Multiplication:")
print("3 times 3 is", 3 * 3)
print("")
print("Division:")
print("3 divided by 3 is", 3 / 3)
print("")
print("Integer Division:")
print("37 divided by 3 is", 37 // 3)
print("")
print("Remainder a.k.a. modulo:")
print("After dividing 37 by 3, the remainder is", 37 % 3)
print("")
print("Addition:")
print("3 plus 3 is", 3 + 3)
print("")
print("Subtraction:")
print("3 minus 3 is", 3 - 3)